### ISSUE TITLE
Docker: No image with latest tag

### ISSUE THREAD

**Issue by chblack42** [rocky-linux/sig-cloud-instance-images#31]
Looks like you no longer have a latest tag for you images on docker, both `docker pull rockylinux` and `docker pull rockylinux:latest` won't work. 

The error message I receive is:
`Error response from daemon: manifest for rockylinux:latest not found: manifest unknown: manifest unknown`

**Comment by NeilHanlon** [comment]
Hi @chblack42 - Thank you for your report. I wrote a more detailed post [here](https://github.com/docker-library/official-images/issues/12797#issuecomment-1186040131) explaining the reason for the change.

For your case, I would recommend you use either `rockylinux:8` or `rockylinux:9` to ensure you are pulling a specific, named version, rather than `latest`.

**Comment by chblack42** [comment]
Thanks for the quick replay and explanation. I understand completely, already rolled back to 8. 

Could you update the docker description (https://hub.docker.com/_/rockylinux?tab=description) to not suggest using latest:
`The rockylinux:latest tag is always the most recent version currently available.`

Not sure what will happen to `docker pull rockylinux` which is suggest at the top of the docker page, I think it alias to `docker pull rockylinux:lastest`

**Comment by NeilHanlon** [comment]
Sure can! Thank you for bringing this up.

Closing as fixed at this time, please re-open if needed.
