### ISSUE TITLE
rockylinux:9 image missing /sbin/init or /usr/sbin/init

### ISSUE THREAD

**Issue by hwdsl2** [rocky-linux/sig-cloud-instance-images#39]
The latest version of rockylinux:9 image is missing /sbin/init (or /usr/sbin/init). Therefore the "Systemd integration" instructions do not work with the latest image version. See: https://hub.docker.com/r/rockylinux/rockylinux

I am aware that the official image is at https://hub.docker.com/_/rockylinux, I'm just linking to the systemd integration section in the link above.

This issue was found on Dec. 21, 2022. The Dec. 17 version of the rockylinux:9 image worked fine and has this file.

@NeilHanlon

Thank you for looking into this possible regression.

**Comment by NeilHanlon** [comment]
Hi - 

I apologize for the extreme latency on responding to this issue. I will investigate adding the init binary to the container in 8.8. It was removed while building the 8.7 images due to systemd polluting the build root and init not being actually a necessary component for most container users, due to container philosophy of running a single thing in a container.

We recognize that users do need/want init containers, and so I would recommend users who need init available use the `ubi` variants of the container images which provide the init/systemd binaries.

We also have a PR open to add ubi-micro and ubi-init variants, the latter of which would automatically have init set as an entrypoint. #42
